### ISSUE TITLE
Please add Licensing Information

### ISSUE THREAD

**Issue by heilkn** [ecsousa/PSPath#2]
Hi!

I have found your tool on PSGallery. I would like to use on my private machine as well as at my company. Could you please add licensing information. I could not find anything.

Kind regards

Konstantin

**Comment by ecsousa** [comment]
License file added on commit fae579ec50497152c0e367a710a10223298e868e

Thank you.

**Comment by heilkn** [comment]
Hi! This is great news. Thank you very much!
